### ISSUE TITLE
Not able to copy username and password inside text field on login window

### ISSUE THREAD

**Issue by nedzad** [FaisalUmair/udemy-downloader-gui#11]
When i open the app i cant copy and paste my username and password. Why is that so?

**Comment by FaisalUmair** [comment]
Hi, 

Copy/paste is not working because there is no native application menu implemented in Udeler as of now. 
The reason for this is there are not enough input fields in the application where you would need to paste something except the login screen.  

But there is no denying it is always good to have copy/paste enabled as some users might need to copy passwords from vault or something like that. 

I will go ahead and make sure copy/paste works in next release. 

Thanks

**Comment by ewoks** [comment]
Unfortunately it is not possible to type some characters in password field as well!
Together with not being able to paste pass this makes it impossible to pass login screen.
One of those problematic character is _"^"_, but maybe there are more.

**Comment by FaisalUmair** [comment]
I just released v1.3.0 which fixes the issue with copy/paste. Download v1.3.0 and try again.

Regarding some characters not being accepted, you can try the same in v1.3.0. If you still cannot type those characters then please open a new issue. 

Thanks

**Comment by ewoks** [comment]
Thanks. Copy/paste works in 1.3.0 so I was able to login. Typing all characters still doesn't work so I will open new issue. This can be closed. Cheers

**Comment by FaisalUmair** [comment]
@Geo-Locale This issue has been fixed in v1.5.4

**Comment by Geo-Locale** [comment]
Thank you Faisal

It is now working again and I appreciate it very much.
