### ISSUE TITLE
You are helping piracy, beleive it or not

### ISSUE THREAD

**Issue by fredyfx** [FaisalUmair/udemy-downloader-gui#111]
It's a good project, helping people to download videos is great, Udemy already does on the mobile. The problem is piracy. There are a lot of users who enrolls to courses and download the full course without hitting play at any video this kind of users wants right away their money back. Guess what, Udemy returns the money.
I arrived here because one friend is an Instructor at Udemy and he published the name of this app.
Sorry if this is uncomfortable to read but you are helping the piracy.
Thanks for reading.
Fredy.

**Comment by FaisalUmair** [comment]
Hello @fredyfx Thanks for you comment. 

My view is that if something can be misused that doesn't necessarily mean it is helping or provoking people to misuse it. I made this software to help people download their courses so that they can view it offline. If there are users with evil intentions, I cannot stop them or cannot remove the software. There are better ways to control piracy, stopping the use of anything is not a solution to stop misuse.
