### ISSUE TITLE
Cannot download courses from business Account?

### ISSUE THREAD

**Issue by ronayumik** [FaisalUmair/udemy-downloader-gui#129]

**Comment by Arjoni** [comment]
It doesn't seem to work with Business accounts.

**Comment by FaisalUmair** [comment]
Hi, I am aware of this issue. I had already added support for this in initial releases of Udeler, but since the recent changes in login strategy. It appears that ee have lost this feature.

I have tried to reproduce this issue, but for my business account it seems to work. I created the business account on trial basis to test this feature. Now in order to reproduce and debug this issue, I would need access to a business account which doesn't work on Udeler (since mine already works).

**If anyone here is willing to share their Udemy business account credentials for the sake of fixing this issue.** , let me know.

**Comment by ronayumik** [comment]
Hmm, what if you tell us what to debug, steps to debug in local? Since it is shared credentials, it feels uncomfortable to share it here 😥

**Comment by tiendungitd** [comment]
it worked well in my udemy business acount.

**Comment by jcortejoso** [comment]
My business account does not seem to work. If I can share some logs or something please let me know.

**Comment by FaisalUmair** [comment]
@ronayumik You can try to clone the repository and enable developer tools (from index.js file) which will allow you to monitor network requests in Udeler application. You can inspect the login request and let me know the result. I can also suggest some changes then if they work, then thats the fix.

@jcortejoso You can also follow the same steps. There are no logs stored as of now. As I have already mentioned in my previous comments that in order for me to fix this completely, I would need somebody who can share their business account (through email probably). For me on my business account it seems to work fine.

**Comment by jcortejoso** [comment]
So as far as I could debug I have enabled the devtools in the app. It seems the authentication endpoint in the app is POST https://www.udemy.com/api-2.0/auth/udemy-auth/login/?fields[user]=access_token, but in my business page is POST to https://<business>.udemy.com/join/login-popup/.

**Comment by ronayumik** [comment]
OK @FaisalUmair, I'll try and check it, and inform the results.
 @jcortejoso thanks dude I'll try changing the endpoint in app

**Comment by FaisalUmair** [comment]
@jcortejoso  I received your email. Thanks for providing you credentials to debug.

I will explain the difference in endpoints, `https://www.udemy.com/api-2.0/auth/udemy-auth/login/?fields[user]=access_token` is used to authenticate no matter what your account type is. 

Now for retrieving the course if we use `https://www.udemy.com/api-2.0/users/me/subscribed-courses?page_size=1` it will try to get courses from normal Udemy account, but since your account is a business account you need to request `https://sngular.udemy.com/api-2.0/users/me/subscribed-courses?page_size=1`. This functionality is already implemented in the app.

I was able to login and view courses from you business account. if you check the is_business checkbox and enter `sngular` in the field you will be able to view your courses. However if you leave it blank or don't check is_business at all, you will still be able to login but it wont show you any courses as your normal account doesn't have any courses.

Let me know if that is also the case with you.

And others please let me know what error you are getting and make sure you are entering correct business name in the field. 

I understand that the business login in the app is quite deceiving sometimes you think you were able to login because you already typed correct details. But as I mentioned before you will still be able to login even if you enter incorrect business name but correct credentials.

**Comment by jcortejoso** [comment]
@FaisalUmair my fault, I was ussing version 1.4.0. Mine is working 🚀

**Comment by ronayumik** [comment]
I didn't know that it is just type [bussiness-name] the login field, now it is working beautifully. Thankyou @FaisalUmair

**Comment by Szewy** [comment]
@FaisalUmair 

I attempt to log in using my udemy business account and there is a message about the incorrect password. Please give me some advise what can I do to log in to your app.

**Comment by santosh-m** [comment]
Hi @FaisalUmair I'm not able to login to my business account through Udeler. But it works fine for my personal account. Could you kindly help ?

I would like to get my understanding right, correct me if I'm wrong. For business Udemy profile we do not have different/new credentials other than the one used for our organisation login. In simpler words I would be using org login credentials to login to Udemy business account. Same should be used for Udeler right ?

Credentials for Udler I used is something like: 
Email : name@myorg.com
Password : myorg_login_pwd
Udemy Business : Yes
Udemy Business Name : myorg 

But it always results in Incorrect password.

@jcortejoso / @ronayumik : Could you suggest any pointers here ? Thanks in advance :)

**Comment by FaisalUmair** [comment]
Hi @santosh-m You are right about the organisation login. It should work.

What version of Udeler are you using?

**Comment by santosh-m** [comment]
@FaisalUmair I'm using version 1.6.2. 

Earlier I was using proxy, so it was saying Connection Failed. When I use normal connection it always says Incorrect Password.

**Comment by FaisalUmair** [comment]
@santosh-m You are on the latest version already.

As of now, the only way I can reproduce this issue and possibly debug it is if you provide me the login credentials. I know most people are not comfortable with sharing credentials and that too of business or organization account. But it is the only way for me to help you.

If you are comfortable, send me an email (available on my GitHub profile) with the login credentials so that I can debug the issue.

**Comment by gruckion** [comment]
I had the same issues. try this to fix.

1. Click on a specific video to watch from browser
2. Close Udeler and reopen
3. Now try to download the video again.

**Comment by Pk161189** [comment]
Try typing only the subdomain in the text box. 

Example - If your company uses https://<your_company>.udemy.com, then type only <your_company> in the textbox and not the complete URL.

**Comment by devbreagan** [comment]
For MAC I am following the correct steps but the login pop-up goes blank

**Comment by firozautomation** [comment]
Dear Faisal, Even i am getting the same blank page, when i am entering udemy for business url and click on Enter Credentials page. I am ready to share my password of my company. Let me know your email id and time so that i can share.

**Comment by SirApollyon** [comment]
I can register with my udemy business account, but in the section "courses", no course is listed, it is empty. any idea?

**Comment by FnZnLi** [comment]
Ok go to udemy right click or F12 for **Inspect**
https://user-images.githubusercontent.com/50474221/57762231-a2f88200-76ee-11e9-9f2a-236ce45c532b.png
Choose **Application** tab, then choose **Cookies**
Take **access_token** form there
https://user-images.githubusercontent.com/50474221/57762361-e6eb8700-76ee-11e9-954f-e75dfe0cab5d.png
While loggin in udeler use **Access Token** and **paste it**
https://i.imgur.com/nITcv04.jpg

**Comment by firozautomation** [comment]
Thank you Faisal. With the above approach i am able to login but for for a moment may be for 2 seconds only i am able to login. Login page is just flickering and going but not fully logged. Please provide me if any other solution for this.

**Comment by zpoll92** [comment]
> I can register with my udemy business account, but in the section "courses", no course is listed, it is empty. any idea?

Same happens here. Is it on purpose?

**Comment by saurabsfdc** [comment]
> Ok go to udemy right click or F12 for **Inspect**
> https://user-images.githubusercontent.com/50474221/57762231-a2f88200-76ee-11e9-9f2a-236ce45c532b.png
> Choose **Application** tab, then choose **Cookies**
> Take **access_token** form there
> https://user-images.githubusercontent.com/50474221/57762361-e6eb8700-76ee-11e9-954f-e75dfe0cab5d.png
> While loggin in udeler use **Access Token** and **paste it**
> https://i.imgur.com/nITcv04.jpg

is the approach working.

**Comment by Kaushikv942** [comment]
@FaisalUmair i am able to login, view all the courses but unable to download. It says you "you do not have access to this content"

**Comment by lliccien** [comment]
> @FaisalUmair i am able to login, view all the courses but unable to download. It says you "you do not have access to this content"
> 
> This happens with token login also.

this happens to me too. Please Help

**Comment by iam-malithmax** [comment]
> > @FaisalUmair i am able to login, view all the courses but unable to download. It says you "you do not have access to this content"
> > 
> > This happens with token login also.
> 
> this happens to me too. Please Help

Hey did you find any other method to download from udemy business?

**Comment by iam-malithmax** [comment]
Hey guys how all you doing..does anyone know other ways to downlod from udemy business? Really appreciate your help.thanks.
