### ISSUE TITLE
[Question] Is it Okay to use the software?

### ISSUE THREAD

**Issue by mrw0lfe** [FaisalUmair/udemy-downloader-gui#158]
Hi, 
this might not be the best place to ask this,but i would like to know if there will be any problem with the account while using this software.(not on your part ofc,but on Udemy's part)I bought a course together with a friend of mine in his account(sice we're studying for  the same thing),and so i don't have to login and logout every time i want to change accounts(cause i try to study at least 2-3 courses at once),plus to be able to listen to the classes everywhere i downloaded the tool.(wich btw it's a fine piece of work).

Im just asking if Udemy doesn't like or usually "goes after" those who use this kind of software.They surely should for those who pirate the content,but in my case,for personal use,is it okay?

**Comment by FaisalUmair** [comment]
Hi @mrw0lfe 
I understand your concern. First of all, **I don't take any responsibility for whatever happens with one's account after using this software.**

But if we speak logic here, then what we really are doing with this software is similar to what Udemy website does, when you use it for viewing your courses.  

You see, when we login to Udemy all your courses are loaded, which is the same behavior we use, and when you select one course it shows its content and you are able to select a video you want to watch and it loads the video in the media player.  
We do the same, but instead of requesting one video at a time, we request multiple at the same time (that's the only difference from normal human interaction) but that's not to say Udemy doesn't have other ways to track users who use such software.

So it really comes down to you, logically nothing should happen to your account as the behavior of your account won't be much different as to if you were browsing the website. But as I said before, **I won't take any responsibilities at all.**

**Comment by mrw0lfe** [comment]
Thank you for the  fast reply and for the explanation about how the program really works.
I tought the program would do a different method,but since what it really does is the same thing as we do manually, i'd think there won't be any problem with it then.

The android app used to download straight MP4's to the user's device,but now they are starting to encrypt them.

Anyway, thanks for the reply :+1:  
I'll take a look at their terms too,but since i now know how the program really works,i doubt it will be something "malicious" to their eyes.But you're right,they're the ones who decide if something's acceptable or not.If something happens the responsibility is on the user of the program,not it's creator.

Regards

**Comment by hellboy81** [comment]
Is this software for downloading payed courses?

**Comment by mrw0lfe** [comment]
> 
> 
> Is this software for downloading payed courses?

It gives you the ability to download courses you already OWN on your account.Both paid and free courses.If they are on your "library" you can download them.But only those on your account.
