### ISSUE TITLE
download failed

### ISSUE THREAD

**Issue by muescha** [FaisalUmair/udemy-downloader-gui#18]
what i do

- i start electron
- i tap on download button
- i tap after a while on pause (still downloaded 1,3GB of data)
- i tap on play button to resume the download
- i get a message "download failed - retry"

what i see:
- download starts from beginning with item 1 of 448 items

what i expected:
- retry to download the last file
- continue with the next not downloaded file

**Comment by FaisalUmair** [comment]
I think this is similar to #16 

Implementing resume from broken download should fix this issue and #16 both.

**Comment by ericnjuki** [comment]
Not sure if this is the same issue but the download immediately fails when internet goes off or a change in network happens, even if just for a second.

**Comment by FaisalUmair** [comment]
If the internet goes off, the default action is it tries to reconnect. In my case when I turn off wifi it retires it for few seconds, if I reconnect it catches up again but if I leave it off for say 20 seconds, it gives up.

But as you mentioned in your case it doesn't even hold for a second, so I guess we have something going on here. What version are you on and what operating system?

**Comment by ericnjuki** [comment]
You're right, i've just tested it a couple of times, it _does_ hold on for some time. Sorry false alarm. But maybe it could pause instead of failing completely and pick up where it left off (this is in line with #16) . 

I do, however have an issue but I don't know how to replicate. I've left some downloads running overnight and when I check next morning it says 'download complete' and all the files are downloaded but some videos (the last few) are only a few bytes big, like 351bytes. Have you experienced this? It's happened 3 times now.

**Comment by FaisalUmair** [comment]
Yeah, we can pause the download instead of ending it. But once we have the resume broken downloads function in place it won't matter at all as the download will still resume from the point it failed.

Coming to your second issue, I haven't actually experienced this myself. However I didn't try downloading courses to the full and checking each file. I think it might be due token invalidation or something or due to file not being resumed correctly after connection lost. Can you leave the course url here so that I can check what could be wrong. 

I also faced some minor issues with the download package in place during the initial releases, I feel like its not working perfectly. But since 1.2.0 improved it quite a lot and in the upcoming release 1.3.0 I have worked on it further. Lets see how it goes from 1.3.0.

**Comment by ericnjuki** [comment]
[Here](https://www.udemy.com/the-complete-guide-to-angular-2/learn/v4/overview) is the link to the course.
Udeler version: 1.2.0
System: Windows 10 Home

**Comment by FaisalUmair** [comment]
Thanks for providing the link. I have released 1.3.0. You can try and see if it changes anything.

**Comment by FaisalUmair** [comment]
Please download the latest version from [here](https://github.com/FaisalUmair/udemy-downloader-gui/releases/latest)  and let me know if the problem has been resolved.

Thanks

**Comment by Shabbash** [comment]
I've solved this problem Manually,
Go to the last folder(section) downloaded,
and delete the file at which the download failed,
Then click retry download.

**Comment by MarvM3** [comment]
Thanks, Shabbash for the circumvention/fix. I deleted the .mp4.mtd file with the latest timestamp in the folder I was downloading to and then just restarted the download on the Retry and PRESTO!, it worked great.

**Comment by farukarslan26** [comment]
yes it works 
thank for solutıon Shabbash

**Comment by KelahKelah** [comment]
The circumvention isn't working  for me, i've tried deleting the latest file still saying  "download failed,click to retry"

**Comment by AzizJalalzai** [comment]
download failed click to retry. this message is come every time when i try to download i also deleted mp4.mtd file still not working.

**Comment by PikarryPham** [comment]
I have tried for 3 times for this error :(( I don't know why I can't continue to download videos
Could anyone please help me fix this error?
![image](https://user-images.githubusercontent.com/43264944/64055970-5ad86f00-cbba-11e9-82c5-49ebdbf7f427.png)

**Comment by aissael12** [comment]
i faced this error. but i fixed it by going to the settings and skip attachments files, and changed the download folder.

**Comment by begumyetiskin** [comment]
Changing the download folder fixed the problem, but it's a problem because the download won't resume where it left off. It starts from the top.

**Comment by igollar-intelipower** [comment]
Stuck in 'building course data' other courses will download fine. any tips would be helpful thanks.
![image](https://user-images.githubusercontent.com/77317992/117647549-b853fa00-b1aa-11eb-84d9-fd94688b0f44.png)
