### ISSUE TITLE
How about subdomains

### ISSUE THREAD

**Issue by walkero-gr** [FaisalUmair/udemy-downloader-gui#31]
I have access to Udemy at a certain subdomain, f.ex. [subdomain].udemy.com 
Is there a way to support such registrations?

**Comment by FaisalUmair** [comment]
I am not sure I understand. Can you add more detail?

**Comment by walkero-gr** [comment]
UDemy makes cooperations with companies to provide specific content at better prices. My company has such a contract. Those companies access Udemy from a specific subdomain, f.ex. apple.udemy.com. Users' access at these sites can see courses that they can't from the main site. F.ex. if I go from the main website a course will ask me to buy it, but from our subdomain it will be totally free.

Does the above make sense?

**Comment by FaisalUmair** [comment]
Yeah that makes sense. Actually I was anticipating this reply. 

But, in order for me to support such registrations, I would need to check how these accounts interact with Udemy servers or if there are any different endpoints in api for such accounts or even if there is an api at all. I don't have any such account so it prevents me from working on that. 

If the api was same it should have beenworking already, but it isn't obviously as that's why we have this issue.

**Comment by FaisalUmair** [comment]
Sounds great! There is a really good chance that Udemy may have kept the api structure same for the subdomain level api and just used the subdomain as host name instead of main domain. 

Since you have the account, you can test it and let me know so that I can implement it in the main repository. Actually we can complete this feature on your fork so that you can verify with each change that its working then later we will merge it with the main repository. 

Also you can take help of developer tools available in the web browser to identify the api endpoints.

**Comment by walkero-gr** [comment]
Hello again.
Today I tried to change the code and support the business packages of udemy.
The problem I have with the login from udeler to these domains is that there is no csrfmiddlewaretoken field, because the login page is generated with JS. Check the following url
https://valin.udemy.com/organization/login/

This is the main problem I have currently with the login procedure. Any idea so far?

**Comment by walkero-gr** [comment]
Closed the issue by mistake. Sorry about that

**Comment by FaisalUmair** [comment]
Hi, There is a `data-module-args` attribute on `.ud-react-loader` element which contains `JSON` where you will find a key named csrf. That is you csrf token. 

Alternatively, you can find the csrf token in the response set-cookie header.

**Comment by walkero-gr** [comment]
Yes, the fork you pointed works just fine... Glad someone implemented this.

**Comment by FaisalUmair** [comment]
Hi @walkero-gr The changes made by @miguelduarte42  are now available in the [latest](https://github.com/FaisalUmair/udemy-downloader-gui/releases/latest) release.
