### ISSUE TITLE
Downloading speed got so slow after downloading 2 or 3 sections 

### ISSUE THREAD

**Issue by nikhil7451** [FaisalUmair/udemy-downloader-gui#37]
why it's happening it got boosted if I pause but just for few seconds,pls fix this.
Thank you for this awesome downloader

**Comment by FaisalUmair** [comment]
The download functionality as of now is not very stable. I am currently using a third party nodejs module for downloading courses. The module has since been updated, but the implementation needs a major overhaul. I will either make some small changes to fix the current issue or update the download manger completely by following the new update of the dependency or make my own downloader which has all the features of current one.

**Comment by nikhil7451** [comment]
thanks ,when will you push the new update

**Comment by dotaxis** [comment]
@FaisalUmair are you willing to outline your idea of the necessary changes for us? I'm sure with a direction in mind someone else could submit a PR for you to build on later.

**Comment by FaisalUmair** [comment]
Hello @dotaxis, Sure man. By saying the downloading functionality is not very stable, I mean sometimes it doesn't resume the download if paused at the verge of download completion. I have actually patched it multiple times so that the download doesn't fail. But I am still not happy with the stability overall as many others here.  And the new feature that is required to is to resume download from the files that were partially downloaded, so that the users can exit the application and start download again at any time. Currently if the download fails it just restarts, you can pause and resume but upon failing it will restart and not resume. 

The library I was using has been updated, but it uses RxJs now which I am not familiar with. So I either have to build my own downloader which can pause/resume and download using multiple threads for faster download speed.

For resuming download from broken files, we can still use the old version as it supports that as well. But for the stability we have to update to new version or create a new downloader.

**Comment by FaisalUmair** [comment]
@nikhil7451  and @dotaxis I will try to push a new update this week which will include the resume support after download fail. Meanwhile @dotaxis  if you can work with the updated version of the dependency it would be great. I will link it [here](https://github.com/tusharmath/Multi-threaded-downloader)

Actually I am not using this dependency directly but a fork of it.

**Comment by nikhil7451** [comment]
thanks @FaisalUmair and @dotaxis for looking in this issue,I don't know much about coding so I can't help really and thanks @FaisalUmair for working on new update of udeler and try in future update to add self build downloader that will be much stable I think.

**Comment by dotaxis** [comment]
@FaisalUmair please don't count on me to look at this right away. Literally got swamped with work right after saying I would work on this.

I'll still do it, but it'll be a few weeks at least.

**Comment by nikhil7451** [comment]
no problem @FaisalUmair work is also very important, work on this one whenever you get time

**Comment by FaisalUmair** [comment]
Hello @dotaxis , @nikhil7451  , I have made the necessary changes required to implement the resume from last session feature. 

Please download the latest version from [here](https://github.com/FaisalUmair/udemy-downloader-gui/releases/latest)  and let me know if the problem has been resolved.

Thanks
