### ISSUE TITLE
Problem with my Udemy Business 

### ISSUE THREAD

**Issue by RAFIKADO** [FaisalUmair/udemy-downloader-gui#391]
i have a problem when i try to connect with my Udemy business i put the link to my udemy business but i don't have acces to put my email and password 
 here is the link to my udemy business

https://indra.udemy.com

please fix it if you can and try you if you have acess to the login page because with my browser it work perfectly

**Comment by RAFIKADO** [comment]
i didn't understand why you respond to the other issue but my issues you  didn't answer  ?

**Comment by FaisalUmair** [comment]
@RAFIKADO I am currently maintaining this software for critical bug fixes only, I reply to the issues which point to a critical bug like recently we had a download error issue for attachments. And even if I find multiple issues on same subject, I sometimes ignore that because I am mostly at work.


And I have previously tried to get in touch with many users who were having issue with business account and that required them to share the account credentials with me, which they couldn't provide.

But since your issue is not specific to the courses or any download error, I will have a look and get back to you.

**Comment by FaisalUmair** [comment]
I tried using the business account url you mentioned. Seems to be working fine for me. I am seeing the login screen. I am not sure if you are referring to something else. But yes one thing I want to add is that the given website takes some time to load. So you might have to wait a bit if you are not seeing the login screen. I will add couple of screenshots here for you to compare (if you are using it the same way)

<img width="662" alt="Screenshot 2020-03-11 at 1 00 20 PM" src="https://user-images.githubusercontent.com/18553256/76393063-c769cd00-6398-11ea-80a4-b708d718a356.png">
<img width="662" alt="Screenshot 2020-03-11 at 1 00 40 PM" src="https://user-images.githubusercontent.com/18553256/76393066-c9cc2700-6398-11ea-9d30-5235a6f419cf.png">

**Comment by RAFIKADO** [comment]
ah no< i have the access to the business acount thank you so much but when i try to download i have this message :
 

<You do not have permission to access this course>

**Comment by RAFIKADO** [comment]
in the site i have the access i mean with my account with the browser but the app when i click on downloadi have this message:

You do not have permission to access this course .
