### ISSUE TITLE
udemy business downloader

### ISSUE THREAD

**Issue by iam-malithmax** [FaisalUmair/udemy-downloader-gui#572]
hey how you guys doing, sorry to bother u guys but i have this problem.i can access to udemy busniess account through udeler.but when i try to download  a course it shows bulding course data and nothing happens.i know this usually it takes little time to build course data.but in this case nothing happens.so do you guys have any solution for this?

**Comment by PratikRJoshi** [comment]
@iam-malithmax I see you have closed this issue. I too am facing the same one since yesterday now. Tried everything I can think of - restarting the application multiple time with and without company VPN being connected before/after starting the application, etc. but nothing has helped. Can you please help elaborate on what worked for you? :)

**Comment by iam-malithmax** [comment]
Hey @PratikRJoshi sorry to hear that.im afraid i can't help you.i still have the same problem too.i closed that only because there are multiple threads about the same issue and i thought its unnessary to ask the same question agian and agian.join the other threads about this issue, i think there will be a solution soon.
